### ISSUE TITLE
Quick translation without pressing ⌘ ⏎. 

### ISSUE THREAD

**Issue by Riemannb** [XInTheDark/raycast-g4f#134]
I would like to know the translation without this window and then pressing ⌘ ⏎. Is this possible?

![image](https://github.com/user-attachments/assets/1389f5f3-7f4e-4e25-96fc-df080b3a4404)

**Comment by XInTheDark** [comment]
Hi! Thanks for opening an issue! Due to the nature of translation, usually in all translation apps you would need to specify the target language to translate to. Could you describe the use case a bit more here - do you have a default language selected and would like the command to automatically translate to that?

**Comment by Riemannb** [comment]
Absolutely correct. I have a keyboard shortcut selected, the text is highlighted, but each time after pressing it, I additionally need to press ⌘ ⏎ to get the translation. I would like to immediately see the result in my default language.

**Comment by XInTheDark** [comment]
@Riemannb Thank you! I've added the option in the latest commit, can you check if it works for you?

**Comment by Riemannb** [comment]
Yeah, everything's great now. Thanks!
