### ISSUE TITLE
[Feature] Interact with the web page by using `{browser-tab}` Dynamic Placeholders in browser tabs.

### ISSUE THREAD

**Issue by lovejavaee** [XInTheDark/raycast-g4f#138]
It would greatly enhance usability if could interact with the active browser tab through [`{browser-tab}`](https://manual.raycast.com/dynamic-placeholders) Dynamic Placeholders by extension [`browser-extension`](https://www.raycast.com/browser-extension)

Two existing extensions already implement this feature. It would be beneficial to reference them.

- [raycast-ollama](https://github.com/raycast/extensions/tree/main/extensions/raycast-ollama)

- [Browser AI Companion](https://github.com/raycast/extensions/blob/main/extensions/browser-ai/README.md)

**Comment by XInTheDark** [comment]
Hi, thanks for the suggestion! I can certainly add it - I took a look at it when the browser extension was released in fact, and had a working version. But I didn't include it because it was kinda buggy when released, and it only supports Chromium browsers - that makes it unusable for Firefox and Safari users (like me :P)

Since you asked though, I’ll go ahead and add it!

**Comment by XInTheDark** [comment]
Hey - it has been added, and will also be included in the next release. Can you check if it works for you? thanks!

**Comment by lovejavaee** [comment]
It works well; I've tested it on Chrome, and I appreciate it.
