### ISSUE TITLE
Display minimum node.js version in README.md

### ISSUE THREAD

**Issue by zisra** [XInTheDark/raycast-g4f#168]
I've had a problem where my node version was too outdated. Because other users could run into the same problem as I did, there should be some kind of disclaimer in the README.md, which reminds them to update to the latest version of node.js (or whatever the minimum version is).

I believe the minimum required version is `20.18.1`, but I could be wrong.

**Comment by XInTheDark** [comment]
Thanks! That's a good idea, since there currently isn't a step telling the user to install nodejs.
I'm not entirely sure what the minimum version is - I believe it's mainly determined by the Raycast API itself and it would probably change over time. To complicate things, Raycast also uses its own node runtime which I believe is currently  `20.18.1`. So I think I'll just put that as the minimum version for now.
